
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 5550129piyuelo
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  ##timeout: 5000

development:
  <<: *default
  database: hello-rails-back-end-development
  username: postgres



test:
  <<: *default
  database: hello-rails-back-end-test
  username: postgres


production:
  <<: *default
  database: hello-rails-back-end-production
  username: postgres

