Message.create!(content: "Hello, world from Argentina!")
Message.create!(content: "Hi there!")
Message.create!(content: "What's up guys?")
Message.create!(content: "Hey Rod!")
Message.create!(content: "Greetings!")